#!/usr/bin/env python3
"""Compare paired rationales generated by two teacher models.

Layer 1 analysis: lexical (ROUGE-L), semantic (BERTScore-F1) and length stats.
Pairs are discovered automatically: for every file under
``dataset/<cat>/<sub>/<dir_b>/<id>.txt`` we look for the matching
``dataset/<cat>/<sub>/<dir_a>/<id>.txt``.
"""
import argparse
import glob
import json
import os
import statistics
from typing import List, Tuple


def find_pairs(dataset_dir: str, dir_a: str, dir_b: str) -> List[Tuple[str, str, str]]:
    pairs = []
    pattern = os.path.join(dataset_dir, "*", "*", dir_b, "*.txt")
    for pb in sorted(glob.glob(pattern)):
        pa = pb.replace(f"/{dir_b}/", f"/{dir_a}/")
        if os.path.exists(pa):
            rel = os.path.relpath(pb, dataset_dir)
            pairs.append((rel, pa, pb))
    return pairs


def read(p: str) -> str:
    with open(p, "r", encoding="utf-8") as f:
        return f.read().strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset_dir", default="dataset")
    ap.add_argument("--dir_a", default="rationales", help="Reference (e.g. GPT-4o)")
    ap.add_argument("--dir_b", default="rationales_claude_sonnet4", help="Hypothesis (e.g. Claude Sonnet 4)")
    ap.add_argument("--out_json", default="rebuttal/rationale_compare_l1.json")
    ap.add_argument("--out_md", default="rebuttal/rationale_compare_l1.md")
    ap.add_argument("--bertscore_model", default="roberta-large")
    ap.add_argument("--no_bertscore", action="store_true")
    args = ap.parse_args()

    pairs = find_pairs(args.dataset_dir, args.dir_a, args.dir_b)
    print(f"[Info] Found {len(pairs)} paired rationales")
    if not pairs:
        return

    refs = [read(pa) for _, pa, _ in pairs]
    hyps = [read(pb) for _, _, pb in pairs]

    # ---- length stats (whitespace tokens) ----
    len_a = [len(r.split()) for r in refs]
    len_b = [len(h.split()) for h in hyps]

    # ---- ROUGE-L ----
    from rouge_score import rouge_scorer
    scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)
    rouge_l = [scorer.score(r, h)["rougeL"].fmeasure for r, h in zip(refs, hyps)]

    # ---- BERTScore-F1 ----
    bert_f1 = None
    if not args.no_bertscore:
        from bert_score import score as bscore
        _, _, F1 = bscore(hyps, refs, model_type=args.bertscore_model, lang="en", verbose=False, rescale_with_baseline=False)
        bert_f1 = F1.tolist()

    def stats(xs):
        return {"mean": statistics.mean(xs), "std": statistics.pstdev(xs), "min": min(xs), "max": max(xs)}

    summary = {
        "n_pairs": len(pairs),
        "dir_a": args.dir_a,
        "dir_b": args.dir_b,
        "length_tokens_a": stats(len_a),
        "length_tokens_b": stats(len_b),
        "rougeL_f1": stats(rouge_l),
    }
    if bert_f1 is not None:
        summary["bertscore_f1"] = stats(bert_f1)
        summary["bertscore_model"] = args.bertscore_model

    os.makedirs(os.path.dirname(args.out_json) or ".", exist_ok=True)
    with open(args.out_json, "w") as f:
        json.dump(summary, f, indent=2)

    # ---- markdown table ----
    lines = [
        f"# Layer 1: Rationale similarity ({args.dir_a} vs {args.dir_b})",
        "",
        f"Paired samples: **{len(pairs)}**",
        "",
        "| Metric | Mean | Std | Min | Max |",
        "|---|---|---|---|---|",
        f"| Length (tokens) — {args.dir_a} | {summary['length_tokens_a']['mean']:.1f} | {summary['length_tokens_a']['std']:.1f} | {summary['length_tokens_a']['min']} | {summary['length_tokens_a']['max']} |",
        f"| Length (tokens) — {args.dir_b} | {summary['length_tokens_b']['mean']:.1f} | {summary['length_tokens_b']['std']:.1f} | {summary['length_tokens_b']['min']} | {summary['length_tokens_b']['max']} |",
        f"| ROUGE-L F1 | {summary['rougeL_f1']['mean']:.4f} | {summary['rougeL_f1']['std']:.4f} | {summary['rougeL_f1']['min']:.4f} | {summary['rougeL_f1']['max']:.4f} |",
    ]
    if bert_f1 is not None:
        b = summary["bertscore_f1"]
        lines.append(f"| BERTScore F1 ({args.bertscore_model}) | {b['mean']:.4f} | {b['std']:.4f} | {b['min']:.4f} | {b['max']:.4f} |")
    with open(args.out_md, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[Done] Wrote {args.out_json} and {args.out_md}")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
